import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import '.././globals.css'

import { cn } from '@/lib/utils';
import AdminLayout from '@/components/Layouts/AdminLayout';
import ECommerce from '@/components/Dashboard/E-commerce';
import Products from '@/components/Products/Products';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <AdminLayout>
        {children}
        <ECommerce />
      </AdminLayout>
    </>
  );
}
